### ISSUE TITLE
Google colab implementation 

### ISSUE THREAD

**Issue by ajay01994** [apls777/kaggle-imaterialist2020-model#1]
Hi Oleg ,

Thanks for your solution , I was wondering if we could make a google colab notebook for your model , is there any other way i can run this model apart from using Google cloud TPU  ? any help over this would be highly appreciated .

Thank you 

Ajay

**Comment by apls777** [comment]
Hi Ajay,

This repo is just a fork of the [TPU Object Detection and Segmentation Framework](https://github.com/tensorflow/tpu/tree/master/models/official/detection) with some extra changes, so it can be run on GPUs as well. Unfortunatelly, I don't have time at the moment to create a Google Colab notebook, but maybe there is somebody already did it for the original framework - then it should not be difficult to just replace it with my code.

Best regards,
Oleg
