### ISSUE TITLE
where is "attribute-head" portion of the model in the config file ?

### ISSUE THREAD

**Issue by mitraavi** [apls777/kaggle-imaterialist2020-model#2]
Hi Oleg,

Thanks! for sharing your model training code using "Spotty", which i found very helpful to train any models in the google cloud.
However, i couldn't identify "attribute-head" portion of your model in the config file, could you please let me know which portion of the config file defines the attribute-head your model ?

Thank You,
Abhi

**Comment by apls777** [comment]
Hi Abhi,

It uses FRCNN head parameters: `frcnn_head`. See [here](https://github.com/apls777/kaggle-imaterialist2020-model/blob/7466434d719b346b04ea0cde8c121d45c1338ce1/tf_tpu_models/official/detection/modeling/architecture/factory.py#L196).

**Comment by mitraavi** [comment]
Thanks Oleg ...Yes...it is more clear now. I'm closing this issue.

Best regards,
Abhi
