### ISSUE TITLE
Publishing your results

### ISSUE THREAD

**Issue by mahdi-darvish** [apls777/kaggle-imaterialist2020-model#3]
Hello sir,

I could not find your email, so I am posting my question here; sorry for the inconvenience. You may delete this issue after reading it.
I am a bachelor student, and I'm trying to publish a paper; I was trying to train this dataset with CenterMask2, but It didn't go so well, and I could not get a reasonable result to publish a paper; I want to know if you are interested in sharing your result as a paper? I can do all work, and you just approve them, and we can send it to a  journal. If this is not something you are interested in, I totally understand. If you have any suggestions, I'll be more than happy to hear.

Best regards,
Mahdi Darvish (MahdyDarvish@gmail.com)

**Comment by apls777** [comment]
Replied on email
