### ISSUE TITLE
Where is valid_coco.json file?

### ISSUE THREAD

**Issue by sh1ng** [apls777/kaggle-imaterialist2020-model#4]

**Comment by apls777** [comment]
It's a validation dataset in the COCO format. First I split the data into training and validation datasets (little more details here: https://www.kaggle.com/c/imaterialist-fashion-2020-fgvc7/discussion/154306), and then I converted the splits to the COCO format. Here I shared the code I used for the conversion: https://gist.github.com/apls777/921c96c1fae8a2eec0f6c7210b061595.
